name: book_demos
description: book_demos
version: 1.0.0+1
environment:
  sdk: '>=2.8.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  # https://pub.dev/packages/fast_noise 用他的柏林噪音
  fast_noise: ^0.1.3+1
  app_lib:
    path: "./plugin/app_lib"
  framework:
    path: "../../flutter_plugin/app_framework"
  # markdown 解析器
  markdown: ^3.0.0
  # ----- only flutter web ---
  # file_picker: ^2.1.4
  # ----- flutter web ---
flutter:
  uses-material-design: true
  assets:
    - assets/h5/
    - assets/h5/assets/
    - assets/h5/assets/js/dependencies/
    - assets/h5/assets/js/dependencies/meyda/
    - assets/images/
    - README.md
    - markdown_sample.md
    


